appname: WenBeego
httpport: 8013
runmode: dev
version: 1.0.0
EnableDocs: false
copyrequestbody: true
timezone: Asia/Shanghai

pgsql:
  host: localhost
  user: postgres
  password: postgres
  dbname: postgres
  port: 5432
  sslmode: disable
  timezone: Asia/Shanghai
pgsql_read:
  read_1:
    host: localhost
    user: postgres
    password: postgres
    dbname: postgres
    port: 5432
    sslmode: disable
    timezone: Asia/Shanghai

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  maxIdle: ""
  timeout: 
  dbNum: 0
  key: ""
  skipEmptyPrefix: ""

log:
  level: debug
  path: ../../temp/logs
  pathMq: ../../temp/logs-mq
  pathTerminal: ../../temp/logs-terminal
  pathUnitTest: ../../temp/logs-unit-test
  maxlines: ""
  maxsize: ""
  daily: true
  maxdays: 15
  rotate: true
  separate: emergency,alert,critical,error,warning,notice,info,debug
logToDbModules:
  - "admin_plat"
  - "admin_mchnt"
  - "api"
branca:
  admin_plat:
    iss: wenBeegoAdminPlat
    aud: wenBeegoAdminPlatUi
    key: rxN07JpyV3ZIWltza6EcUvP9uRjw1eKF
    exp: 86400
    expRemark: 24*60*60
queue:
  type: rabbitmq
  default_queue: wen_beego_tasks
  redis:
    host: 127.0.0.1
    dbNum: 0
    port: 6379
    password: ""
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest
    exchange:     machinery_exchange
    exchangeType: direct
    bindingKey:   machinery_task
