definitions:
  auth_dto.LoginDto:
    properties:
      authCode:
        example: "1234"
        type: string
      authCodeId:
        example: J4HGcl1gCLIdPm6T
        type: string
      authCodeType:
        example: captcha
        type: string
      password:
        example: "123456"
        maxLength: 20
        minLength: 6
        type: string
      phone:
        example: "15912345678"
        type: string
    required:
    - password
    - phone
    type: object
  dto.RespDataListDto:
    properties:
      currentPage:
        type: integer
      list: {}
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  dto.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin_plat/auth-menu/get-async-routes:
    get:
      consumes:
      - application/json
      description: 获取异步路由
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取异步路由
      tags:
      - admin
  /admin_plat/auth-params/model-params:
    get:
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 获取参数-模型常量参数
      tags:
      - 参数
  /admin_plat/auth-plat/change-unit:
    get:
      consumes:
      - application/json
      description: 切换组织
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 切换组织
      tags:
      - admin
  /admin_plat/auth-plat/get-user-unit:
    get:
      consumes:
      - application/json
      description: 获取用户组织单位
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户组织单位
      tags:
      - admin
  /admin_plat/auth/get-captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/dto.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取验证码
      tags:
      - admin
  /admin_plat/auth/login:
    post:
      consumes:
      - application/json
      description: admin用户登录
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth_dto.LoginDto'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/dto.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 登录
      tags:
      - admin
  /admin_plat/auth/logout:
    post:
      consumes:
      - application/json
      description: admin退出登录
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/dto.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 退出登录
      tags:
      - admin
  /admin_plat/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: 刷新token
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/dto.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - ApiKeyAuth: []
      summary: 刷新token
      tags:
      - admin
  /admin_plat/system-unit/get:
    get:
      consumes:
      - application/json
      description: 获取内部组织管理
      parameters:
      - description: 父级ID
        in: query
        name: parentUnitId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RespDataListDto'
      summary: 获取内部组织管理
      tags:
      - 系统管理-内部组织管理
swagger: "2.0"
