definitions:
  dto.LoginDto:
    properties:
      authCode:
        example: "1234"
        type: string
      authCodeType:
        example: captcha
        type: string
      password:
        example: "123456"
        maxLength: 20
        minLength: 6
        type: string
      phone:
        example: "15912345678"
        type: string
    required:
    - password
    - phone
    type: object
  helper.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/auth/login:
    post:
      consumes:
      - application/json
      description: admin用户登录
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/helper.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
      summary: 登录
      tags:
      - admin
  /admin/auth/logout:
    post:
      consumes:
      - application/json
      description: admin退出登录
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/helper.Response'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - ApiKeyAuth: []
      summary: 退出登录
      tags:
      - admin
swagger: "2.0"
