
networks:
  nextcloud_network:
    external: true

volumes:
  postgres_data2:  
    name: postgres_data2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\postgres\data
      
  postgres_config2: 
    name: postgres_config2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\postgres\config
      
  redis-data2:
    name: redis-data2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\redis\data
  redis-config2:
    name: redis-config2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\redis\config
  redis-log2:
    name: redis-log2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\redis\log

  rabbitmq-data2:
    name: rabbitmq-data2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\rabbitmq\data
  rabbitmq-cinfig2:
    name: rabbitmq-cinfig2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\\rabbitmq\cinfig2

services:
  # c_golang:
  #   build:
  #     context: ./0Dockerfiles
  #     dockerfile: ./0Dockerfiles/Dockerfile-golang
  #   container_name: c_dev_golang
  #   user: "0:0" 
  #   privileged: true
  #   environment:
  #     TZ: Asia/Shanghai            # 时区设置
  #   volumes:
  #     - ..:/app                    # 挂载项目代码
  #     - ../doc:/app/wen-admin-docker #覆盖排除wen-admin-docker目录
  #   ports:
  #     - "8013:8013"               # 端口映射
  #   networks:
  #     - nextcloud_network
  #   restart: unless-stopped        # 自动重启策略
  #   working_dir: /app              # 设置工作目录
  #   command: tail -f /dev/null     # 保持容器运行（用于开发环境）

  c_postgresql:
    build:
      context: ./0Dockerfiles
      dockerfile: ./0Dockerfiles/Dockerfile-pg
    container_name: c_dev_postgresql
    user: "0:0" 
    privileged: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
      TZ: Asia/Shanghai            # 时区设置
      TZ1: Asia/Shanghai
    volumes:
      - postgres_data2:/bitnami/postgresql/data
      - postgres_config2:/opt/bitnami/postgresql/conf
    ports:
      - "5432:5432"               # 端口映射
    networks:
      - nextcloud_network
    restart: unless-stopped        # 自动重启策略


  redis:
    build:
      context: ./0Dockerfiles
      dockerfile: ./0Dockerfiles/Dockerfile-redis
    container_name: c_dev_redis70
    init: true
    environment:
      CONTAINER_NAME: "c_dev_redis70"
      TZ: "Asia/Shanghai"
    volumes:
      - redis-data2:/data
      # 注意这里需要先  /usr/local/app/redis/conf  新建redis.conf文件  redis.conf文件可从http://www.redis.cn/下载
      - redis-config2:/usr/local/etc/redis
      - redis-log2:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    networks:
      - nextcloud_network
      
  rabbitmq:
    build:
      context: ./0Dockerfiles
      dockerfile: ./0Dockerfiles/Dockerfile-rabbitmq
    container_name: c_dev_rabbitmq
    environment:
      RABBITMQ_USERNAME: 'guest'
      RABBITMQ_PASSWORD: 'guest'
      TZ: "Asia/Shanghai"
    volumes:
      - rabbitmq-data2:/var/lib/rabbitmq
      - rabbitmq-cinfig2:/etc/rabbitmq
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nextcloud_network
